<div style="border: 1px solid; width: 98%; padding: 10px; box-shadow: 10px 5px 5px black;">

# <center>  S2.04-R2.08 - TP 0 <br/> Opérations matricielles / numpy.array <br/> sur extrait des données Parcoursup

## Objectifs
S'initier à la manipulation d'un tableau de données en Python, sur un extrait du fichier de la SAé 2.04 :

- import d'un fichier .csv avec le package `pandas` (partie A)
- extraction et opérations sur les lignes/colonnes du `numpy.array` obtenu (parties B et D)
- application des représentations graphiques vues en statistiques (partie C)
- vers une régression linéaire multiple (partie E).

##  A. Import d'un fichier .csv via `pandas`, et passage vers un `numpy.array`

<div class="alert alert-danger" role="alert">

Tout d'abord, on va utiliser les packages Python suivants :

In [1]:
import numpy as np
import pandas as pd

<div class="alert alert-danger" role="alert">

Le package `pandas` permet d'importer des tableaux de données sous un format appelé `DataFrame`, constitué des données en format `numpy.array`, et intégrant en plus les noms des lignes et des colonnes. 

<div class="alert alert-info" role="alert">

**1.** Télécharger sur Moodle le fichier `ParcoursupLannion.csv` et le placer dans le même dossier que ce TP. Puis importer ce fichier à l'aide des commandes suivantes :

In [2]:
df_lannion =  pd.read_csv("ParcoursupLannion.csv")

# affichage des premières lignes du DataFrame
print(df_lannion.head())

# affichage des noms des colonnes du DataFrame
print(df_lannion.columns)

                                Filière de formation  \
0                          BTS - Services - Tourisme   
1  BUT - Information communication Parcours commu...   
2  BTS - Services - Services informatiques aux or...   
3            BTS - Production - Systèmes photoniques   
4                BTS - Production - Electrotechnique   

                    Etablissement Code_UAI_etablissement  \
0  Lycée Saint - Joseph - Bossuet               0220102S   
1                I.U.T de Lannion               0221036G   
2           Lycée Felix Le Dantec               0220023F   
3           Lycée Felix Le Dantec               0220023F   
4           Lycée Felix Le Dantec               0220023F   

  Coordonnées GPS de la formation  Capacité de l’établissement par formation  \
0               48.7285, -3.45597                                         35   
1               48.7584, -3.45128                                         29   
2                48.731, -3.44693                             

<div class="alert alert-info" role="alert">

**2.** On peut extraire l'ensemble des données sous forme de `numpy.array`. Ou, cela va nous intéresser : n'extraire que les données numériques, sur lequelles on pourra réaliser des statistiques :

In [9]:
# Passage en numpy.array des données contenues dans le DataFrame :
arr_complet_lannion =  df_lannion.to_numpy()

# Extraction en DataFrame des colonnes contenant des données numériques :
df_num_lannion = df_lannion._get_numeric_data()
print(df_num_lannion.columns)

# Passer ensuite en numpy.array les données de df_num_lannion :
arr_lannion = df_num_lannion.to_numpy()
print(arr_lannion)


Index(['Capacité de l’établissement par formation',
       'Effectif total des candidats pour une formation',
       'Dont effectif des candidates pour une formation',
       'Effectif total des candidats ayant accepté la proposition de l’établissement (admis)',
       'Dont effectif des candidates admises',
       'Effectif des admis néo bacheliers',
       'Dont effectif des admis néo bacheliers sans mention au bac',
       'Dont effectif des admis néo bacheliers avec mention Assez Bien au bac',
       'Dont effectif des admis néo bacheliers avec mention Bien au bac',
       'Dont effectif des admis néo bacheliers avec mention Très Bien au bac',
       'Dont effectif des admis issus de la même académie'],
      dtype='str')
[[  35  245  176   17   13   12    6    6    0    0   10]
 [  29  345  261   29   25   27    1   14    9    3   22]
 [  35 1024  180   32    1   21    7    8    5    1   19]
 [  15  108   36   10    4    6    2    4    0    0    5]
 [  24  135   10   10    1    6 

## B. Lignes et colonnes d'un `numpy.array`, opérations élémentaires

<div class="alert alert-danger" role="alert">

Pour faire cette partie, vous trouverez des rappels sur les `numpy.array` dans l'Aide-Mémoire Python présent sur l'espace Moodle de R2.08, + précisément dans la partie "Module Numpy" de cet aide-mémoire. 

<div class="alert alert-info" role="alert">

**3.** A l'aide des commandes d'accès à des portions du tableau, créer un tableau `C` contenant la colonne de la capacité des formations lannionaises, puis un tableau `Adm` contenant le nombre d'admis.es dans chaque formation, et un tableau `Adme` contenant le nombre d'amisEs dans chaque formation.

In [28]:
C = arr_lannion[:,1]
print(C)

Adm = arr_lannion[:,3]
print(Adm)

Adme = arr_lannion[:,4]
print(Adme)

[ 245  345 1024  108  135  713 3881   28  765  637  735  806 1104  810]
[ 17  29  32  10  10  28  51   7  72  56  29  27 119  98]
[13 25  1  4  1 11 41  3  4 10  3 16 10 20]


<div class="alert alert-info" role="alert">

**4.** A l'aide des tableaux `Adm, Adme` et `C` et des opérations +,  –,  *  ou  / :
- créer un tableau `D` contenant la différence entre la capacité de chaque formation et le nombre d'admis,
- créer un tableau `P_A` contenant la proportion (entre 0 et 1) d'étudiantEs admises pour chaque formation.

Créer un tableau `P_TB` contenant la proportion de mentions Bien et Très Bien parmi les néo-bachelier admis dans chaque formation.

In [ ]:
D = C-Adm
print(D)

P_A = (Adme/Adm)*100
print(P_A)

P_TB = (arr_lannion[:,8] + arr_lannion[:,9]) / arr_lannion[:,5]
...

[ 228  316  992   98  125  685 3830   21  693  581  706  779  985  712]
[76.47058824 86.20689655  3.125      40.         10.         39.28571429
 80.39215686 42.85714286  5.55555556 17.85714286 10.34482759 59.25925926
  8.40336134 20.40816327]


Ellipsis

<div class="alert alert-info" role="alert">

**5.** Quelle est la formation Lannionaise ayant la + forte proportion d'étudiantEs ? Celle ayant la + faible proportion d'étudiantEs ?

Réponses : la formation la plus forte est le BTS info-com et la + faible le BTS SIO

    

<div class="alert alert-info" role="alert">

**6.** A l'aide des tableaux `Adm, Adme` et `C`, calculer le pourcentage d'étudiantEs parmi les étudiants arrivé.es à Lannion en 2022. On pourra s'aider de la partie "Opérations Mathématiques" de l'Aide-Mémoire Python.

In [32]:
print((sum(Adme)/sum(Adm))*100)

27.692307692307693


## C. Représentations graphiques

<div class="alert alert-danger" role="alert">

On rappelle qu'on a vu comment faire un diagramme en bâtons et une boite à moustaches dans la Fiche 1B. Pour le diagramme en bâtons, on avait utilisé <a href="cpge.frama.io/fiches-cpge/Python/Graphiques/2-Histogramme/"> ce tutoriel</a>.

<div class="alert alert-info" role="alert">

**7.** Faire un diagramme en bâtons des capacités des formations lannionnaises, en faisant des bâtons de largeur 10. Pour faire le tableau `inter`, on pourra utiliser `np.arange` ou `np.linspace`.

In [ ]:
import matplotlib.pyplot as plt

inter = plt.bar

...

<div class="alert alert-info" role="alert">

**8.** Faire un diagramme en bâtons des proportions d'admisEs (parmis les admis) des formations lannionaises. Vous choisirez un tableau `inter` vous paraissant intéressant, probablement avec la fonction `np.linspace`.

<div class="alert alert-info" role="alert">

**9.** Faire une boite à moustaches des proportions d'admisEs (parmis les admis) des formations lannionaises.

<div class="alert alert-info" role="alert">

**10.** Créer un tableau P_C contenant la proportion de candidatEs parmi les candidats de chaque formation.

<div class="alert alert-info" role="alert">

**11.** Représenter sur le même graphique la boite à moustaches des proportions d'admisEs, et une nouvelle boite à moustaches représentant la proportion de candidatEs parmi l'ensemble des candidats pour les différentes formations.

## D. Opérations matricielles sur les `numpy.array`

<div class="alert alert-info" role="alert">

**12.** Utiliser un attribut de `arr_lannion` pour obtenir le nombre `N` de formations disponibles à Lannion sur Parcoursup (sur l'Aide-Mémoire, partie "Attributs d'un tableau T").

In [ ]:
N = ...
print(N)    

<div class="alert alert-info" role="alert">

**13.** Créer un `numpy.array` `X` rempli de "1", ayant 3 colonnes et `N` lignes (sur l'Aide-Mémoire, partie "Création de tableaux").

In [ ]:
X = ...
print(X)

<div class="alert alert-info" role="alert">

**14.** Changer la 2e colonne de `X` en y mettant le contenu du tableau `P_TB`.
Puis changer la 3e colonne de `X` pour y mettre le taux d'admission de chaque formation : c'est-à-dire le nombre d'admis.es divisé par le nombre de candidat.es.

In [ ]:
...

print(X)

<div class="alert alert-info" role="alert">


**15.** Créer `tX`, la matrice transposée $^t X$ de `X`. Puis calculer le produit matriciel $^tX X$ (dans l'Aide-Mémoire, se servir de la partie "Opérations mathématiques").

In [ ]:
...

print(tX)

...

<div class="alert alert-info" role="alert">


**16.** Calculer l'inverse $ (^t X X )^{-1}$ du produit matriciel calculé ci-dessus (dans l'Aide-Mémoire, voir la partie "`numpy.linalg`: méthodes d'algèbre linéaire").

In [ ]:
import numpy.linalg as la

...


## E. Une régression linéaire multiple 

<div class="alert alert-danger" role="alert">

Dans cette partie, on va calculer en Python les paramètres de la régression linéaire suivante :
- Population : formations situées à Lannion sur Parcoursup
- Variable endogène : proportion de filles parmi les candidat.es à chaque formation
- Variables explicatives : la proportion de mentions Bien et Très bien dans les admis de chaque formation, et le taux d'admission de chaque formation.

On rappelle que les calculs à effectuer pour obtenir les paramètres sont expliqués dans le Cours 3, pages 31-32.

<div class="alert alert-info" role="alert">

**17.** La matrice $X$ des variables explicatives a déjà été créée dans la partie D. La matrice $Y$ a aussi déjà été créée précédemment, sous un autre nom, comment s'appelait-elle ?

In [ ]:
Y = 

<div class="alert alert-info" role="alert">

**18.** A l'aide des calculs déjà effectués dans la partie D, calculer la matrice `A` des paramètres de la régression linéaire.

In [ ]:
A = ...

print(A)

<div class="alert alert-info" role="alert">

**19.** Interpréter les paramètres obtenus (voir Cours 3, page 30).

Réponse : 


